import { retrieveConflictContents } from "./get-files"; // Adjust path as needed
import { Octokit } from "octokit";

describe("retrieveConflictContents", () => {
  let mockGraphql: jest.Mock;
  let mockOctokit: Octokit;
  let consoleErrorSpy: jest.SpyInstance;

  beforeEach(() => {
    jest.clearAllMocks();

    mockGraphql = jest.fn();
    mockOctokit = {
      graphql: mockGraphql,
    } as unknown as Octokit;

    // Spy on console.error to keep test output clean during the error test
    consoleErrorSpy = jest.spyOn(console, "error").mockImplementation(() => {});
  });

  afterEach(() => {
    consoleErrorSpy.mockRestore();
  });

  it("returns an empty array and makes no API calls if fileList is empty", async () => {
    const result = await retrieveConflictContents([], "shaA", "shaT", "shaF", "owner", "repo", mockOctokit);

    expect(result).toEqual([]);
    expect(mockGraphql).not.toHaveBeenCalled();
  });

  it("constructs the correct GraphQL query and maps the response for a single chunk", async () => {
    const files = ["file1.ts", "file2.ts"];

    // Mock the GraphQL response based on how the aliases are structured
    mockGraphql.mockResolvedValueOnce({
      repository: {
        ancestor_0: { text: "ancestor 1" },
        target_0: { text: "target 1" },
        feature_0: { text: "feature 1" },
        
        // Simulate file2 not existing in the ancestor (null blob) and deleted in feature
        ancestor_1: null,
        target_1: { text: "target 2" },
        feature_1: null, 
      },
    });

    const result = await retrieveConflictContents(
      files, "shaA", "shaT", "shaF", "owner", "repo", mockOctokit
    );

    // Verify exactly 1 network call was made
    expect(mockGraphql).toHaveBeenCalledTimes(1);

    // Verify the mapping handled the nulls correctly
    expect(result).toHaveLength(2);
    expect(result[0]).toEqual({
      fileName: "file1.ts",
      ancestorContent: "ancestor 1",
      targetContent: "target 1",
      featureContent: "feature 1",
    });
    expect(result[1]).toEqual({
      fileName: "file2.ts",
      ancestorContent: null,
      targetContent: "target 2",
      featureContent: null,
    });
  });

  it("chunks requests into batches of 15 files and runs them concurrently", async () => {
    // Generate an array of 32 files (should result in 3 chunks: 15, 15, 2)
    const files = Array.from({ length: 32 }, (_, i) => `file${i}.ts`);

    // Mock the response for all 3 chunk calls
    mockGraphql.mockResolvedValue({
      repository: {
        ancestor_0: { text: "mock" },
      },
    });

    await retrieveConflictContents(
      files, "shaA", "shaT", "shaF", "owner", "repo", mockOctokit
    );

    // Verify chunking logic
    expect(mockGraphql).toHaveBeenCalledTimes(3);

    // Optionally verify the variables passed to the calls
    expect(mockGraphql).toHaveBeenNthCalledWith(1, expect.any(String), { owner: "owner", repo: "repo" });
  });

  it("escapes double quotes in filenames to prevent GraphQL syntax errors", async () => {
    const files = ['weird"name.txt'];

    mockGraphql.mockResolvedValueOnce({ repository: {} });

    await retrieveConflictContents(
      files, "shaA", "shaT", "shaF", "owner", "repo", mockOctokit
    );

    // Extract the raw query string generated by the function
    const querySent = mockGraphql.mock.calls[0][0];

    // Verify the quote was safely escaped with a backslash
    expect(querySent).toContain('weird\\"name.txt');
  });

  it("logs and rethrows errors if the GraphQL request fails", async () => {
    const files = ["file.ts"];
    const mockError = new Error("GraphQL timeout");

    mockGraphql.mockRejectedValueOnce(mockError);

    await expect(
      retrieveConflictContents(files, "shaA", "shaT", "shaF", "owner", "repo", mockOctokit)
    ).rejects.toThrow("GraphQL timeout");

    expect(consoleErrorSpy).toHaveBeenCalledWith("GraphQL Batch Content Fetch Error:", "GraphQL timeout");
  });
});